server:
#  servlet:
#    context-path: /index  #修改上下文路径
  port: 80  #修改端口

### 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shixun
    username: root
    password: root
  servlet:
    multipart:
      ### 配置文件上传大小
      max-file-size: 10MB
      max-request-size: 10MB

### mybatis配置   数据库语句映射文件配置
mybatis:
  mapper-locations: classpath:org/example/mapper/*.xml  #映射文件地址
  type-aliases-package: org.example.entity  #定义类别名

### 密码错误上限
passwordErrorCount: 3


pagehelper:
#  方言
  helper-dialect: mysql
#  分页合理化
  reasonable: true

pageSize: 3


